[2022-06-11 19:38:37,392] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: T-dbt-job-dimensions.dbt_clone_and_transform-dimensions scheduled__2022-06-11T17:32:40.246424+00:00 [queued]>
[2022-06-11 19:38:37,401] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: T-dbt-job-dimensions.dbt_clone_and_transform-dimensions scheduled__2022-06-11T17:32:40.246424+00:00 [queued]>
[2022-06-11 19:38:37,401] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-11 19:38:37,401] {taskinstance.py:1357} INFO - Starting attempt 4 of 5
[2022-06-11 19:38:37,401] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-11 19:38:37,416] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): dbt_clone_and_transform-dimensions> on 2022-06-11 17:32:40.246424+00:00
[2022-06-11 19:38:37,422] {standard_task_runner.py:52} INFO - Started process 240 to run task
[2022-06-11 19:38:37,426] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'T-dbt-job-dimensions', 'dbt_clone_and_transform-dimensions', 'scheduled__2022-06-11T17:32:40.246424+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/docker_job/dbt_model.py', '--cfg-path', '/tmp/tmpyy_x3tvz', '--error-file', '/tmp/tmprvcxdj3z']
[2022-06-11 19:38:37,426] {standard_task_runner.py:80} INFO - Job 11: Subtask dbt_clone_and_transform-dimensions
[2022-06-11 19:38:37,439] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/configuration.py:525: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-06-11 19:38:37,480] {task_command.py:370} INFO - Running <TaskInstance: T-dbt-job-dimensions.dbt_clone_and_transform-dimensions scheduled__2022-06-11T17:32:40.246424+00:00 [running]> on host e926c0944008
[2022-06-11 19:38:37,549] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=samuelolle@yahoo.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=T-dbt-job-dimensions
AIRFLOW_CTX_TASK_ID=dbt_clone_and_transform-dimensions
AIRFLOW_CTX_EXECUTION_DATE=2022-06-11T17:32:40.246424+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-11T17:32:40.246424+00:00
[2022-06-11 19:38:37,550] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-11 19:38:37,550] {subprocess.py:74} INFO - Running command: ['bash', '-c', " rm -rf /tmp/dimensions && mkdir /tmp/dimensions                            && cp -r /tmp/dbt /tmp/dimensions/dbt                             && cd /tmp/dimensions/dbt && python3 -m venv venv                             && export PIP_USER=false                             && *** /tmp/dimensions/dbt/venv/bin/activate                             && pip  install --quiet --upgrade pip setuptools                             && pip3 install --quiet 'MarkupSafe<=2.0.1' 'dbt-postgres' 'dbt-core'                             && dbt --version && deactivate                             && cd /tmp/dimensions/dbt && *** /tmp/dimensions/dbt/venv/bin/activate                             && dbt deps --profiles-dir /tmp/dimensions/dbt/ && dbt seed --profiles-dir /tmp/dimensions/dbt/                             && dbt run --models dimensions --profiles-dir /tmp/dimensions/dbt/"]
[2022-06-11 19:38:37,568] {subprocess.py:85} INFO - Output:
[2022-06-11 19:39:13,298] {subprocess.py:92} INFO - Core:
[2022-06-11 19:39:13,298] {subprocess.py:92} INFO -   - installed: 1.1.0
[2022-06-11 19:39:13,298] {subprocess.py:92} INFO -   - latest:    1.1.0 - [32mUp to date![0m
[2022-06-11 19:39:13,298] {subprocess.py:92} INFO - 
[2022-06-11 19:39:13,298] {subprocess.py:92} INFO - Plugins:
[2022-06-11 19:39:13,298] {subprocess.py:92} INFO -   - postgres: 1.1.0 - [32mUp to date![0m
[2022-06-11 19:39:16,412] {subprocess.py:92} INFO - [0m19:39:16  Running with dbt=1.1.0
[2022-06-11 19:39:16,413] {subprocess.py:92} INFO - [0m19:39:16  Warning: No packages were found in packages.yml
[2022-06-11 19:39:19,562] {subprocess.py:92} INFO - [0m19:39:19  Running with dbt=1.1.0
[2022-06-11 19:39:19,580] {subprocess.py:92} INFO - [0m19:39:19  Partial parse save file not found. Starting full parse.
[2022-06-11 19:39:20,288] {subprocess.py:92} INFO - [0m19:39:20  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any re***s.
[2022-06-11 19:39:20,288] {subprocess.py:92} INFO - There are 1 unused configuration paths:
[2022-06-11 19:39:20,288] {subprocess.py:92} INFO - - seeds.SAM
[2022-06-11 19:39:20,288] {subprocess.py:92} INFO - 
[2022-06-11 19:39:20,301] {subprocess.py:92} INFO - [0m19:39:20  Found 4 models, 6 tests, 0 snapshots, 0 analyses, 171 macros, 4 operations, 0 seed files, 4 ***s, 0 exposures, 0 metrics
[2022-06-11 19:39:20,304] {subprocess.py:92} INFO - [0m19:39:20
[2022-06-11 19:39:20,305] {subprocess.py:92} INFO - [0m19:39:20  [WARNING]: Nothing to do. Try checking your model configs and model specification args
[2022-06-11 19:39:20,312] {subprocess.py:92} INFO - [0m19:39:20
[2022-06-11 19:39:20,313] {subprocess.py:92} INFO - [0m19:39:20  Completed successfully
[2022-06-11 19:39:20,313] {subprocess.py:92} INFO - [0m19:39:20
[2022-06-11 19:39:20,314] {subprocess.py:92} INFO - [0m19:39:20  Done. PASS=0 WARN=0 ERROR=0 SKIP=0 TOTAL=0
[2022-06-11 19:39:23,443] {subprocess.py:92} INFO - [0m19:39:23  Running with dbt=1.1.0
[2022-06-11 19:39:23,477] {subprocess.py:92} INFO - [0m19:39:23  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any re***s.
[2022-06-11 19:39:23,477] {subprocess.py:92} INFO - There are 1 unused configuration paths:
[2022-06-11 19:39:23,477] {subprocess.py:92} INFO - - seeds.SAM
[2022-06-11 19:39:23,477] {subprocess.py:92} INFO - 
[2022-06-11 19:39:23,491] {subprocess.py:92} INFO - [0m19:39:23  Found 4 models, 6 tests, 0 snapshots, 0 analyses, 171 macros, 4 operations, 0 seed files, 4 ***s, 0 exposures, 0 metrics
[2022-06-11 19:39:23,493] {subprocess.py:92} INFO - [0m19:39:23
[2022-06-11 19:39:23,554] {subprocess.py:92} INFO - [0m19:39:23  Concurrency: 4 threads (target='dev')
[2022-06-11 19:39:23,554] {subprocess.py:92} INFO - [0m19:39:23
[2022-06-11 19:39:23,563] {subprocess.py:92} INFO - [0m19:39:23  1 of 1 START view model analytics_objects_analytics_objects.dim_date ........... [RUN]
[2022-06-11 19:39:23,636] {subprocess.py:92} INFO - [0m19:39:23  1 of 1 OK created view model analytics_objects_analytics_objects.dim_date ...... [CREATE VIEW in 0.07s]
[2022-06-11 19:39:23,669] {subprocess.py:92} INFO - [0m19:39:23
[2022-06-11 19:39:23,670] {subprocess.py:92} INFO - [0m19:39:23  Running 4 on-run-end hooks
[2022-06-11 19:39:23,676] {subprocess.py:92} INFO - [0m19:39:23  1 of 4 START hook: SAM.on-run-end.0 ............................................ [RUN]
[2022-06-11 19:39:23,678] {subprocess.py:92} INFO - [0m19:39:23  Database error while running on-run-end
[2022-06-11 19:39:23,680] {subprocess.py:92} INFO - [0m19:39:23  Encountered an error:
[2022-06-11 19:39:23,680] {subprocess.py:92} INFO - Database Error
[2022-06-11 19:39:23,680] {subprocess.py:92} INFO -   schema "analytics_object" does not exist
[2022-06-11 19:39:23,892] {subprocess.py:96} INFO - Command exited with return code 2
[2022-06-11 19:39:23,911] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-06-11 19:39:23,914] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=T-dbt-job-dimensions, task_id=dbt_clone_and_transform-dimensions, execution_date=20220611T173240, start_date=20220611T193837, end_date=20220611T193923
[2022-06-11 19:39:23,927] {standard_task_runner.py:97} ERROR - Failed to execute job 11 for task dbt_clone_and_transform-dimensions (Bash command failed. The command returned a non-zero exit code 2.; 240)
[2022-06-11 19:39:23,943] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-11 19:39:23,975] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
