[2022-06-18 09:13:02,699] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Job-price_test_scale.price_test_scale-apple-iphone-xr-128gb-schwarz_h_6266 scheduled__2022-06-17T22:42:09.574729+00:00 [queued]>
[2022-06-18 09:13:04,927] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Job-price_test_scale.price_test_scale-apple-iphone-xr-128gb-schwarz_h_6266 scheduled__2022-06-17T22:42:09.574729+00:00 [queued]>
[2022-06-18 09:13:05,245] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-18 09:13:05,701] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2022-06-18 09:13:05,707] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-18 09:15:10,776] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): price_test_scale-apple-iphone-xr-128gb-schwarz_h_6266> on 2022-06-17 22:42:09.574729+00:00
[2022-06-18 09:15:11,115] {standard_task_runner.py:52} INFO - Started process 2941 to run task
[2022-06-18 09:15:12,150] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Job-price_test_scale', 'price_test_scale-apple-iphone-xr-128gb-schwarz_h_6266', 'scheduled__2022-06-17T22:42:09.574729+00:00', '--job-id', '396', '--raw', '--subdir', 'DAGS_FOLDER/docker_job/price_test_scale.py', '--cfg-path', '/tmp/tmpur83jt7g', '--error-file', '/tmp/tmpotv0kx22']
[2022-06-18 09:15:12,203] {standard_task_runner.py:80} INFO - Job 396: Subtask price_test_scale-apple-iphone-xr-128gb-schwarz_h_6266
[2022-06-18 09:16:06,693] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/configuration.py:525: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-06-18 09:16:13,010] {task_command.py:370} INFO - Running <TaskInstance: Job-price_test_scale.price_test_scale-apple-iphone-xr-128gb-schwarz_h_6266 scheduled__2022-06-17T22:42:09.574729+00:00 [running]> on host 31bbb70af43b
[2022-06-18 09:17:35,946] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=samuel.momoh-olle@asgoodasnew.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Job-price_test_scale
AIRFLOW_CTX_TASK_ID=price_test_scale-apple-iphone-xr-128gb-schwarz_h_6266
AIRFLOW_CTX_EXECUTION_DATE=2022-06-17T22:42:09.574729+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-17T22:42:09.574729+00:00
[2022-06-18 09:17:36,053] {logging_mixin.py:115} INFO - /opt/airflow
[2022-06-18 09:18:46,683] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/docker_job/price_test_scale.py", line 124, in run_from_class
    ppd = ProductPriceData(driver=webdriver.Chrome(executable_path="dags/docker_job/chromedriver", options=options))
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    service_log_path, service, keep_alive)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 98, in __init__
    options=options)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
Stacktrace:
#0 0x56094d438f33 <unknown>
#1 0x56094d183118 <unknown>
#2 0x56094d1a9282 <unknown>
#3 0x56094d1a57c6 <unknown>
#4 0x56094d1a1d5a <unknown>
#5 0x56094d1dcd3a <unknown>
#6 0x56094d1d6e63 <unknown>
#7 0x56094d1ac82a <unknown>
#8 0x56094d1ad985 <unknown>
#9 0x56094d47d4cd <unknown>
#10 0x56094d4815ec <unknown>
#11 0x56094d46771e <unknown>
#12 0x56094d482238 <unknown>
#13 0x56094d45c870 <unknown>
#14 0x56094d49e608 <unknown>
#15 0x56094d49e788 <unknown>
#16 0x56094d4b8f1d <unknown>
#17 0x7fb0c197bea7 <unknown>

[2022-06-18 09:19:29,081] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Job-price_test_scale, task_id=price_test_scale-apple-iphone-xr-128gb-schwarz_h_6266, execution_date=20220617T224209, start_date=20220618T091302, end_date=20220618T091929
[2022-06-18 09:19:30,169] {standard_task_runner.py:97} ERROR - Failed to execute job 396 for task price_test_scale-apple-iphone-xr-128gb-schwarz_h_6266 (Message: unknown error: DevToolsActivePort file doesn't exist
Stacktrace:
#0 0x56094d438f33 <unknown>
#1 0x56094d183118 <unknown>
#2 0x56094d1a9282 <unknown>
#3 0x56094d1a57c6 <unknown>
#4 0x56094d1a1d5a <unknown>
#5 0x56094d1dcd3a <unknown>
#6 0x56094d1d6e63 <unknown>
#7 0x56094d1ac82a <unknown>
#8 0x56094d1ad985 <unknown>
#9 0x56094d47d4cd <unknown>
#10 0x56094d4815ec <unknown>
#11 0x56094d46771e <unknown>
#12 0x56094d482238 <unknown>
#13 0x56094d45c870 <unknown>
#14 0x56094d49e608 <unknown>
#15 0x56094d49e788 <unknown>
#16 0x56094d4b8f1d <unknown>
#17 0x7fb0c197bea7 <unknown>
; 2941)
[2022-06-18 09:19:30,257] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-18 09:19:30,521] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
