[2022-06-15 21:23:51,550] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Job-product_prices_testers.product_prices_testers manual__2022-06-15T21:23:48.105213+00:00 [queued]>
[2022-06-15 21:23:51,559] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Job-product_prices_testers.product_prices_testers manual__2022-06-15T21:23:48.105213+00:00 [queued]>
[2022-06-15 21:23:51,559] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-15 21:23:51,559] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2022-06-15 21:23:51,559] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-15 21:23:51,570] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): product_prices_testers> on 2022-06-15 21:23:48.105213+00:00
[2022-06-15 21:23:51,575] {standard_task_runner.py:52} INFO - Started process 295 to run task
[2022-06-15 21:23:51,578] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Job-product_prices_testers', 'product_prices_testers', 'manual__2022-06-15T21:23:48.105213+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/docker_job/price_test.py', '--cfg-path', '/tmp/tmpjgamx_mh', '--error-file', '/tmp/tmp99nr02g1']
[2022-06-15 21:23:51,578] {standard_task_runner.py:80} INFO - Job 6: Subtask product_prices_testers
[2022-06-15 21:23:51,630] {task_command.py:370} INFO - Running <TaskInstance: Job-product_prices_testers.product_prices_testers manual__2022-06-15T21:23:48.105213+00:00 [running]> on host 3c1ac2e19971
[2022-06-15 21:23:51,699] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=samuel.momoh-olle@asgoodasnew.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Job-product_prices_testers
AIRFLOW_CTX_TASK_ID=product_prices_testers
AIRFLOW_CTX_EXECUTION_DATE=2022-06-15T21:23:48.105213+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-15T21:23:48.105213+00:00
[2022-06-15 21:23:51,701] {logging_mixin.py:115} INFO - /opt/airflow
[2022-06-15 21:23:51,709] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    creationflags=self.creationflags)
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/docker_job/price_test.py", line 124, in run_from_class
    ppd = ProductPriceData(driver=webdriver.Chrome(executable_path="chromedriver", options=options))
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    service_log_path, service, keep_alive)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions. Please see https://chromedriver.chromium.org/home

[2022-06-15 21:23:51,722] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Job-product_prices_testers, task_id=product_prices_testers, execution_date=20220615T212348, start_date=20220615T212351, end_date=20220615T212351
[2022-06-15 21:23:51,733] {standard_task_runner.py:97} ERROR - Failed to execute job 6 for task product_prices_testers (Message: 'chromedriver' executable may have wrong permissions. Please see https://chromedriver.chromium.org/home
; 295)
[2022-06-15 21:23:51,753] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-15 21:23:51,784] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
