[2022-06-17 20:13:02,147] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Job-pts.pts-Papple-iphone-xs-max-64gb-space-grau_h_6251 manual__2022-06-17T20:12:59.782916+00:00 [queued]>
[2022-06-17 20:13:02,213] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Job-pts.pts-Papple-iphone-xs-max-64gb-space-grau_h_6251 manual__2022-06-17T20:12:59.782916+00:00 [queued]>
[2022-06-17 20:13:02,213] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 20:13:02,213] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2022-06-17 20:13:02,213] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 20:13:02,238] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): pts-Papple-iphone-xs-max-64gb-space-grau_h_6251> on 2022-06-17 20:12:59.782916+00:00
[2022-06-17 20:13:02,251] {standard_task_runner.py:52} INFO - Started process 5995 to run task
[2022-06-17 20:13:02,276] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Job-pts', 'pts-Papple-iphone-xs-max-64gb-space-grau_h_6251', 'manual__2022-06-17T20:12:59.782916+00:00', '--job-id', '300', '--raw', '--subdir', 'DAGS_FOLDER/docker_job/price_scale.py', '--cfg-path', '/tmp/tmpgxkj4zjp', '--error-file', '/tmp/tmpa_560lx2']
[2022-06-17 20:13:02,276] {standard_task_runner.py:80} INFO - Job 300: Subtask pts-Papple-iphone-xs-max-64gb-space-grau_h_6251
[2022-06-17 20:13:02,985] {task_command.py:370} INFO - Running <TaskInstance: Job-pts.pts-Papple-iphone-xs-max-64gb-space-grau_h_6251 manual__2022-06-17T20:12:59.782916+00:00 [running]> on host 2d9e52ec85d2
[2022-06-17 20:13:03,619] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=samuel.momoh-olle@asgoodasnew.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Job-pts
AIRFLOW_CTX_TASK_ID=pts-Papple-iphone-xs-max-64gb-space-grau_h_6251
AIRFLOW_CTX_EXECUTION_DATE=2022-06-17T20:12:59.782916+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-17T20:12:59.782916+00:00
[2022-06-17 20:14:14,176] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/docker_job/price_scale.py", line 115, in test
    ppd = ProductPriceData(driver=webdriver.Chrome(executable_path="dags/docker_job/chromedriver", options=options))
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    service_log_path, service, keep_alive)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 98, in __init__
    options=options)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
Stacktrace:
#0 0x557c1c033f33 <unknown>
#1 0x557c1bd7e118 <unknown>
#2 0x557c1bda4282 <unknown>
#3 0x557c1bda07c6 <unknown>
#4 0x557c1bd9cd5a <unknown>
#5 0x557c1bdd7d3a <unknown>
#6 0x557c1bdd1e63 <unknown>
#7 0x557c1bda782a <unknown>
#8 0x557c1bda8985 <unknown>
#9 0x557c1c0784cd <unknown>
#10 0x557c1c07c5ec <unknown>
#11 0x557c1c06271e <unknown>
#12 0x557c1c07d238 <unknown>
#13 0x557c1c057870 <unknown>
#14 0x557c1c099608 <unknown>
#15 0x557c1c099788 <unknown>
#16 0x557c1c0b3f1d <unknown>
#17 0x7fc790376ea7 <unknown>

[2022-06-17 20:14:16,251] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Job-pts, task_id=pts-Papple-iphone-xs-max-64gb-space-grau_h_6251, execution_date=20220617T201259, start_date=20220617T201302, end_date=20220617T201416
[2022-06-17 20:14:16,502] {standard_task_runner.py:97} ERROR - Failed to execute job 300 for task pts-Papple-iphone-xs-max-64gb-space-grau_h_6251 (Message: unknown error: DevToolsActivePort file doesn't exist
Stacktrace:
#0 0x557c1c033f33 <unknown>
#1 0x557c1bd7e118 <unknown>
#2 0x557c1bda4282 <unknown>
#3 0x557c1bda07c6 <unknown>
#4 0x557c1bd9cd5a <unknown>
#5 0x557c1bdd7d3a <unknown>
#6 0x557c1bdd1e63 <unknown>
#7 0x557c1bda782a <unknown>
#8 0x557c1bda8985 <unknown>
#9 0x557c1c0784cd <unknown>
#10 0x557c1c07c5ec <unknown>
#11 0x557c1c06271e <unknown>
#12 0x557c1c07d238 <unknown>
#13 0x557c1c057870 <unknown>
#14 0x557c1c099608 <unknown>
#15 0x557c1c099788 <unknown>
#16 0x557c1c0b3f1d <unknown>
#17 0x7fc790376ea7 <unknown>
; 5995)
[2022-06-17 20:14:16,570] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-17 20:14:18,337] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
