[2022-06-12 02:50:19,512] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: T-dbt-job-dimensions.dbt_clone_and_transform-dimensions manual__2022-06-12T02:44:50.320608+00:00 [queued]>
[2022-06-12 02:50:19,523] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: T-dbt-job-dimensions.dbt_clone_and_transform-dimensions manual__2022-06-12T02:44:50.320608+00:00 [queued]>
[2022-06-12 02:50:19,523] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-12 02:50:19,523] {taskinstance.py:1357} INFO - Starting attempt 3 of 3
[2022-06-12 02:50:19,523] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-12 02:50:19,537] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): dbt_clone_and_transform-dimensions> on 2022-06-12 02:44:50.320608+00:00
[2022-06-12 02:50:19,542] {standard_task_runner.py:52} INFO - Started process 2584 to run task
[2022-06-12 02:50:19,545] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'T-dbt-job-dimensions', 'dbt_clone_and_transform-dimensions', 'manual__2022-06-12T02:44:50.320608+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/docker_job/dbt_model.py', '--cfg-path', '/tmp/tmpp_32ij9j', '--error-file', '/tmp/tmpm4haau8_']
[2022-06-12 02:50:19,546] {standard_task_runner.py:80} INFO - Job 75: Subtask dbt_clone_and_transform-dimensions
[2022-06-12 02:50:19,603] {task_command.py:370} INFO - Running <TaskInstance: T-dbt-job-dimensions.dbt_clone_and_transform-dimensions manual__2022-06-12T02:44:50.320608+00:00 [running]> on host e926c0944008
[2022-06-12 02:50:19,665] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=samuelolle@yahoo.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=T-dbt-job-dimensions
AIRFLOW_CTX_TASK_ID=dbt_clone_and_transform-dimensions
AIRFLOW_CTX_EXECUTION_DATE=2022-06-12T02:44:50.320608+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-12T02:44:50.320608+00:00
[2022-06-12 02:50:19,666] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-12 02:50:19,667] {subprocess.py:74} INFO - Running command: ['bash', '-c', " rm -rf /tmp/dimensions && mkdir /tmp/dimensions                            && cp -r /tmp/dbt /tmp/dimensions/dbt                             && cd /tmp/dimensions/dbt && python3 -m venv venv                             && export PIP_USER=false                             && *** /tmp/dimensions/dbt/venv/bin/activate                             && pip  install --quiet --upgrade pip setuptools                             && pip3 install --quiet 'MarkupSafe<=2.0.1' 'dbt-postgres' 'dbt-core'                             && dbt --version && deactivate                             && cd /tmp/dimensions/dbt && *** /tmp/dimensions/dbt/venv/bin/activate                             && dbt deps --profiles-dir /tmp/dimensions/dbt/ && dbt seed --profiles-dir /tmp/dimensions/dbt/                             && dbt run --models dimensions --profiles-dir /tmp/dimensions/dbt/"]
[2022-06-12 02:50:19,677] {subprocess.py:85} INFO - Output:
[2022-06-12 02:50:53,054] {subprocess.py:92} INFO - Core:
[2022-06-12 02:50:53,055] {subprocess.py:92} INFO -   - installed: 1.1.0
[2022-06-12 02:50:53,055] {subprocess.py:92} INFO -   - latest:    1.1.0 - [32mUp to date![0m
[2022-06-12 02:50:53,055] {subprocess.py:92} INFO - 
[2022-06-12 02:50:53,055] {subprocess.py:92} INFO - Plugins:
[2022-06-12 02:50:53,055] {subprocess.py:92} INFO -   - postgres: 1.1.0 - [32mUp to date![0m
[2022-06-12 02:50:55,816] {subprocess.py:92} INFO - [0m02:50:55  Running with dbt=1.1.0
[2022-06-12 02:50:55,818] {subprocess.py:92} INFO - [0m02:50:55  Warning: No packages were found in packages.yml
[2022-06-12 02:50:58,500] {subprocess.py:92} INFO - [0m02:50:58  Running with dbt=1.1.0
[2022-06-12 02:50:58,513] {subprocess.py:92} INFO - [0m02:50:58  Partial parse save file not found. Starting full parse.
[2022-06-12 02:50:59,127] {subprocess.py:92} INFO - [0m02:50:59  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any re***s.
[2022-06-12 02:50:59,127] {subprocess.py:92} INFO - There are 1 unused configuration paths:
[2022-06-12 02:50:59,127] {subprocess.py:92} INFO - - seeds.SAM
[2022-06-12 02:50:59,128] {subprocess.py:92} INFO - 
[2022-06-12 02:50:59,142] {subprocess.py:92} INFO - [0m02:50:59  Found 5 models, 6 tests, 0 snapshots, 0 analyses, 172 macros, 7 operations, 0 seed files, 4 ***s, 0 exposures, 0 metrics
[2022-06-12 02:50:59,143] {subprocess.py:92} INFO - [0m02:50:59
[2022-06-12 02:50:59,144] {subprocess.py:92} INFO - [0m02:50:59  [WARNING]: Nothing to do. Try checking your model configs and model specification args
[2022-06-12 02:50:59,149] {subprocess.py:92} INFO - [0m02:50:59
[2022-06-12 02:50:59,150] {subprocess.py:92} INFO - [0m02:50:59  Completed successfully
[2022-06-12 02:50:59,150] {subprocess.py:92} INFO - [0m02:50:59
[2022-06-12 02:50:59,151] {subprocess.py:92} INFO - [0m02:50:59  Done. PASS=0 WARN=0 ERROR=0 SKIP=0 TOTAL=0
[2022-06-12 02:51:01,943] {subprocess.py:92} INFO - [0m02:51:01  Running with dbt=1.1.0
[2022-06-12 02:51:01,976] {subprocess.py:92} INFO - [0m02:51:01  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any re***s.
[2022-06-12 02:51:01,977] {subprocess.py:92} INFO - There are 1 unused configuration paths:
[2022-06-12 02:51:01,977] {subprocess.py:92} INFO - - seeds.SAM
[2022-06-12 02:51:01,977] {subprocess.py:92} INFO - 
[2022-06-12 02:51:01,990] {subprocess.py:92} INFO - [0m02:51:01  Found 5 models, 6 tests, 0 snapshots, 0 analyses, 172 macros, 7 operations, 0 seed files, 4 ***s, 0 exposures, 0 metrics
[2022-06-12 02:51:01,991] {subprocess.py:92} INFO - [0m02:51:01
[2022-06-12 02:51:02,054] {subprocess.py:92} INFO - [0m02:51:02  Concurrency: 4 threads (target='dev')
[2022-06-12 02:51:02,054] {subprocess.py:92} INFO - [0m02:51:02
[2022-06-12 02:51:02,063] {subprocess.py:92} INFO - [0m02:51:02  1 of 2 START table model analytics_dim.dim_date ................................ [RUN]
[2022-06-12 02:51:02,069] {subprocess.py:92} INFO - [0m02:51:02  2 of 2 START incremental model analytics_dim.dim_walls ......................... [RUN]
[2022-06-12 02:51:02,226] {subprocess.py:92} INFO - [0m02:51:02  1 of 2 OK created table model analytics_dim.dim_date ........................... [SELECT 546 in 0.16s]
[2022-06-12 02:51:02,232] {subprocess.py:92} INFO - [0m02:51:02  2 of 2 OK created incremental model analytics_dim.dim_walls .................... [INSERT 0 0 in 0.16s]
[2022-06-12 02:51:02,284] {subprocess.py:92} INFO - [0m02:51:02
[2022-06-12 02:51:02,284] {subprocess.py:92} INFO - [0m02:51:02  Running 7 on-run-end hooks
[2022-06-12 02:51:02,292] {subprocess.py:92} INFO - [0m02:51:02  1 of 7 START hook: SAM.on-run-end.0 ............................................ [RUN]
[2022-06-12 02:51:02,296] {subprocess.py:92} INFO - [0m02:51:02  1 of 7 OK hook: SAM.on-run-end.0 ............................................... [ALTER DEFAULT PRIVILEGES in 0.00s]
[2022-06-12 02:51:02,300] {subprocess.py:92} INFO - [0m02:51:02  2 of 7 START hook: SAM.on-run-end.1 ............................................ [RUN]
[2022-06-12 02:51:02,303] {subprocess.py:92} INFO - [0m02:51:02  2 of 7 OK hook: SAM.on-run-end.1 ............................................... [ALTER DEFAULT PRIVILEGES in 0.00s]
[2022-06-12 02:51:02,307] {subprocess.py:92} INFO - [0m02:51:02  3 of 7 START hook: SAM.on-run-end.2 ............................................ [RUN]
[2022-06-12 02:51:02,309] {subprocess.py:92} INFO - [0m02:51:02  3 of 7 OK hook: SAM.on-run-end.2 ............................................... [ALTER DEFAULT PRIVILEGES in 0.00s]
[2022-06-12 02:51:02,313] {subprocess.py:92} INFO - [0m02:51:02  4 of 7 START hook: SAM.on-run-end.3 ............................................ [RUN]
[2022-06-12 02:51:02,315] {subprocess.py:92} INFO - [0m02:51:02  4 of 7 OK hook: SAM.on-run-end.3 ............................................... [ALTER DEFAULT PRIVILEGES in 0.00s]
[2022-06-12 02:51:02,318] {subprocess.py:92} INFO - [0m02:51:02  5 of 7 START hook: SAM.on-run-end.4 ............................................ [RUN]
[2022-06-12 02:51:02,321] {subprocess.py:92} INFO - [0m02:51:02  5 of 7 OK hook: SAM.on-run-end.4 ............................................... [ALTER DEFAULT PRIVILEGES in 0.00s]
[2022-06-12 02:51:02,324] {subprocess.py:92} INFO - [0m02:51:02  6 of 7 START hook: SAM.on-run-end.5 ............................................ [RUN]
[2022-06-12 02:51:02,327] {subprocess.py:92} INFO - [0m02:51:02  6 of 7 OK hook: SAM.on-run-end.5 ............................................... [ALTER DEFAULT PRIVILEGES in 0.00s]
[2022-06-12 02:51:02,333] {subprocess.py:92} INFO - [0m02:51:02  7 of 7 START hook: SAM.on-run-end.6 ............................................ [RUN]
[2022-06-12 02:51:02,335] {subprocess.py:92} INFO - [0m02:51:02  Database error while running on-run-end
[2022-06-12 02:51:02,336] {subprocess.py:92} INFO - [0m02:51:02  Encountered an error:
[2022-06-12 02:51:02,336] {subprocess.py:92} INFO - Database Error
[2022-06-12 02:51:02,336] {subprocess.py:92} INFO -   syntax error at or near "analytics_dim"
[2022-06-12 02:51:02,336] {subprocess.py:92} INFO -   LINE 2: analytics_dim
[2022-06-12 02:51:02,336] {subprocess.py:92} INFO -           ^
[2022-06-12 02:51:02,511] {subprocess.py:96} INFO - Command exited with return code 2
[2022-06-12 02:51:02,527] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-06-12 02:51:02,531] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=T-dbt-job-dimensions, task_id=dbt_clone_and_transform-dimensions, execution_date=20220612T024450, start_date=20220612T025019, end_date=20220612T025102
[2022-06-12 02:51:02,543] {standard_task_runner.py:97} ERROR - Failed to execute job 75 for task dbt_clone_and_transform-dimensions (Bash command failed. The command returned a non-zero exit code 2.; 2584)
[2022-06-12 02:51:02,562] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-12 02:51:02,606] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
