[2022-06-16 07:58:49,259] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Job-product_prices_testers.product_prices_testers scheduled__2022-06-16T05:19:49.287355+00:00 [queued]>
[2022-06-16 07:58:49,266] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Job-product_prices_testers.product_prices_testers scheduled__2022-06-16T05:19:49.287355+00:00 [queued]>
[2022-06-16 07:58:49,266] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-16 07:58:49,266] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2022-06-16 07:58:49,266] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-16 07:58:49,276] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): product_prices_testers> on 2022-06-16 05:19:49.287355+00:00
[2022-06-16 07:58:49,280] {standard_task_runner.py:52} INFO - Started process 5951 to run task
[2022-06-16 07:58:49,283] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Job-product_prices_testers', 'product_prices_testers', 'scheduled__2022-06-16T05:19:49.287355+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/docker_job/price_test.py', '--cfg-path', '/tmp/tmp7twtcncw', '--error-file', '/tmp/tmpsyrb0j0v']
[2022-06-16 07:58:49,283] {standard_task_runner.py:80} INFO - Job 139: Subtask product_prices_testers
[2022-06-16 07:58:49,294] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/configuration.py:525: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-06-16 07:58:49,329] {task_command.py:370} INFO - Running <TaskInstance: Job-product_prices_testers.product_prices_testers scheduled__2022-06-16T05:19:49.287355+00:00 [running]> on host 2d9e52ec85d2
[2022-06-16 07:58:49,386] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=samuel.momoh-olle@asgoodasnew.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Job-product_prices_testers
AIRFLOW_CTX_TASK_ID=product_prices_testers
AIRFLOW_CTX_EXECUTION_DATE=2022-06-16T05:19:49.287355+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-16T05:19:49.287355+00:00
[2022-06-16 07:58:49,389] {logging_mixin.py:115} INFO - /opt/airflow
[2022-06-16 07:58:50,034] {logging_mixin.py:115} INFO - https://www.handyverkauf.net/apple-iphone-x-64gb-space-grau_h_5143
[2022-06-16 07:59:21,087] {logging_mixin.py:115} INFO - https://www.handyverkauf.net/apple-iphone-x-256gb-space-grau_h_5145
[2022-06-16 07:59:52,839] {logging_mixin.py:115} INFO - https://www.handyverkauf.net/apple-iphone-xs-64gb-space-grau_h_6242
[2022-06-16 08:00:23,617] {logging_mixin.py:115} INFO - https://www.handyverkauf.net/apple-iphone-xs-256gb-space-grau_h_6245
[2022-06-16 08:00:56,552] {logging_mixin.py:115} INFO - https://www.handyverkauf.net/apple-iphone-xs-512gb-space-grau_h_6248
[2022-06-16 08:01:27,809] {logging_mixin.py:115} INFO - https://www.handyverkauf.net/apple-iphone-xs-max-64gb-space-grau_h_6251
[2022-06-16 08:02:00,192] {logging_mixin.py:115} INFO - https://www.handyverkauf.net/apple-iphone-xs-max-256gb-space-grau_h_6254
[2022-06-16 08:07:48,938] {logging_mixin.py:115} INFO - Message: timeout: Timed out receiving message from renderer: 296.146
  (Session info: headless chrome=102.0.5005.115)
Stacktrace:
#0 0x561434cd9f33 <unknown>
#1 0x561434a24118 <unknown>
#2 0x561434a0f008 <unknown>
#3 0x561434a0dc0f <unknown>
#4 0x561434a0e19c <unknown>
#5 0x561434a1c5ff <unknown>
#6 0x561434a1d162 <unknown>
#7 0x561434a2b24d <unknown>
#8 0x561434a2e66a <unknown>
#9 0x561434a0e5c6 <unknown>
#10 0x561434a2af54 <unknown>
#11 0x561434a8b6e8 <unknown>
#12 0x561434a77e63 <unknown>
#13 0x561434a4d82a <unknown>
#14 0x561434a4e985 <unknown>
#15 0x561434d1e4cd <unknown>
#16 0x561434d225ec <unknown>
#17 0x561434d0871e <unknown>
#18 0x561434d23238 <unknown>
#19 0x561434cfd870 <unknown>
#20 0x561434d3f608 <unknown>
#21 0x561434d3f788 <unknown>
#22 0x561434d59f1d <unknown>
#23 0x7f7ea09c4ea7 <unknown>
[2022-06-16 08:07:51,260] {logging_mixin.py:115} INFO - https://www.handyverkauf.net/apple-iphone-xs-max-512gb-space-grau_h_6257
[2022-06-16 08:08:58,447] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/docker_job/price_test.py", line 132, in run_from_class
    webdriver.Chrome(executable_path="dags/docker_job/chromedriver", options=options),
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    service_log_path, service, keep_alive)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 98, in __init__
    options=options)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
Stacktrace:
#0 0x562062d11f33 <unknown>
#1 0x562062a5c118 <unknown>
#2 0x562062a82282 <unknown>
#3 0x562062a7e7c6 <unknown>
#4 0x562062a7ad5a <unknown>
#5 0x562062ab5d3a <unknown>
#6 0x562062aafe63 <unknown>
#7 0x562062a8582a <unknown>
#8 0x562062a86985 <unknown>
#9 0x562062d564cd <unknown>
#10 0x562062d5a5ec <unknown>
#11 0x562062d4071e <unknown>
#12 0x562062d5b238 <unknown>
#13 0x562062d35870 <unknown>
#14 0x562062d77608 <unknown>
#15 0x562062d77788 <unknown>
#16 0x562062d91f1d <unknown>
#17 0x7f9ddbd91ea7 <unknown>

[2022-06-16 08:09:05,232] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Job-product_prices_testers, task_id=product_prices_testers, execution_date=20220616T051949, start_date=20220616T075849, end_date=20220616T080904
[2022-06-16 08:09:14,057] {standard_task_runner.py:97} ERROR - Failed to execute job 139 for task product_prices_testers (Message: unknown error: DevToolsActivePort file doesn't exist
Stacktrace:
#0 0x562062d11f33 <unknown>
#1 0x562062a5c118 <unknown>
#2 0x562062a82282 <unknown>
#3 0x562062a7e7c6 <unknown>
#4 0x562062a7ad5a <unknown>
#5 0x562062ab5d3a <unknown>
#6 0x562062aafe63 <unknown>
#7 0x562062a8582a <unknown>
#8 0x562062a86985 <unknown>
#9 0x562062d564cd <unknown>
#10 0x562062d5a5ec <unknown>
#11 0x562062d4071e <unknown>
#12 0x562062d5b238 <unknown>
#13 0x562062d35870 <unknown>
#14 0x562062d77608 <unknown>
#15 0x562062d77788 <unknown>
#16 0x562062d91f1d <unknown>
#17 0x7f9ddbd91ea7 <unknown>
; 5951)
[2022-06-16 08:09:14,869] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-16 08:09:16,064] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
