[2022-06-18 09:35:48,268] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Job-price_test_scale.price_test_scale-apple-iphone-xs-512gb-space-grau_h_6248 scheduled__2022-06-17T22:42:09.574729+00:00 [queued]>
[2022-06-18 09:35:48,298] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Job-price_test_scale.price_test_scale-apple-iphone-xs-512gb-space-grau_h_6248 scheduled__2022-06-17T22:42:09.574729+00:00 [queued]>
[2022-06-18 09:35:48,298] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-18 09:35:48,298] {taskinstance.py:1357} INFO - Starting attempt 3 of 6
[2022-06-18 09:35:48,298] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-18 09:35:48,672] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): price_test_scale-apple-iphone-xs-512gb-space-grau_h_6248> on 2022-06-17 22:42:09.574729+00:00
[2022-06-18 09:35:49,149] {standard_task_runner.py:52} INFO - Started process 4156 to run task
[2022-06-18 09:35:49,581] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Job-price_test_scale', 'price_test_scale-apple-iphone-xs-512gb-space-grau_h_6248', 'scheduled__2022-06-17T22:42:09.574729+00:00', '--job-id', '412', '--raw', '--subdir', 'DAGS_FOLDER/docker_job/price_test_scale.py', '--cfg-path', '/tmp/tmpofck08oq', '--error-file', '/tmp/tmpf3wnujlv']
[2022-06-18 09:35:49,687] {standard_task_runner.py:80} INFO - Job 412: Subtask price_test_scale-apple-iphone-xs-512gb-space-grau_h_6248
[2022-06-18 09:36:06,580] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/configuration.py:525: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-06-18 09:36:24,496] {task_command.py:370} INFO - Running <TaskInstance: Job-price_test_scale.price_test_scale-apple-iphone-xs-512gb-space-grau_h_6248 scheduled__2022-06-17T22:42:09.574729+00:00 [running]> on host 2d9e52ec85d2
[2022-06-18 09:38:35,607] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=samuel.momoh-olle@asgoodasnew.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Job-price_test_scale
AIRFLOW_CTX_TASK_ID=price_test_scale-apple-iphone-xs-512gb-space-grau_h_6248
AIRFLOW_CTX_EXECUTION_DATE=2022-06-17T22:42:09.574729+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-17T22:42:09.574729+00:00
[2022-06-18 09:38:35,649] {logging_mixin.py:115} INFO - /opt/airflow
[2022-06-18 09:40:48,846] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/docker_job/price_test_scale.py", line 124, in run_from_class
    ppd = ProductPriceData(driver=webdriver.Chrome(executable_path="dags/docker_job/chromedriver", options=options))
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    service_log_path, service, keep_alive)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 98, in __init__
    options=options)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
Stacktrace:
#0 0x55e263475f33 <unknown>
#1 0x55e2631c0118 <unknown>
#2 0x55e2631e6282 <unknown>
#3 0x55e2631e27c6 <unknown>
#4 0x55e2631ded5a <unknown>
#5 0x55e263219d3a <unknown>
#6 0x55e263213e63 <unknown>
#7 0x55e2631e982a <unknown>
#8 0x55e2631ea985 <unknown>
#9 0x55e2634ba4cd <unknown>
#10 0x55e2634be5ec <unknown>
#11 0x55e2634a471e <unknown>
#12 0x55e2634bf238 <unknown>
#13 0x55e263499870 <unknown>
#14 0x55e2634db608 <unknown>
#15 0x55e2634db788 <unknown>
#16 0x55e2634f5f1d <unknown>
#17 0x7f630dd2bea7 <unknown>

[2022-06-18 09:40:49,669] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Job-price_test_scale, task_id=price_test_scale-apple-iphone-xs-512gb-space-grau_h_6248, execution_date=20220617T224209, start_date=20220618T093548, end_date=20220618T094049
[2022-06-18 09:40:49,760] {standard_task_runner.py:97} ERROR - Failed to execute job 412 for task price_test_scale-apple-iphone-xs-512gb-space-grau_h_6248 (Message: unknown error: DevToolsActivePort file doesn't exist
Stacktrace:
#0 0x55e263475f33 <unknown>
#1 0x55e2631c0118 <unknown>
#2 0x55e2631e6282 <unknown>
#3 0x55e2631e27c6 <unknown>
#4 0x55e2631ded5a <unknown>
#5 0x55e263219d3a <unknown>
#6 0x55e263213e63 <unknown>
#7 0x55e2631e982a <unknown>
#8 0x55e2631ea985 <unknown>
#9 0x55e2634ba4cd <unknown>
#10 0x55e2634be5ec <unknown>
#11 0x55e2634a471e <unknown>
#12 0x55e2634bf238 <unknown>
#13 0x55e263499870 <unknown>
#14 0x55e2634db608 <unknown>
#15 0x55e2634db788 <unknown>
#16 0x55e2634f5f1d <unknown>
#17 0x7f630dd2bea7 <unknown>
; 4156)
[2022-06-18 09:40:49,770] {local_task_job.py:221} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2022-06-18 09:40:49,792] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 4156. PIDs of all processes in the group: [4156]
[2022-06-18 09:40:49,793] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 4156
[2022-06-18 09:40:49,793] {process_utils.py:75} INFO - Process psutil.Process(pid=4156, status='terminated', exitcode=1, started='09:35:48') (4156) terminated with exit code 1
