[2022-06-17 20:13:03,688] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Job-pts.pts-Papple-iphone-xr-64gb-schwarz_h_6260 manual__2022-06-17T20:12:59.782916+00:00 [queued]>
[2022-06-17 20:13:03,716] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Job-pts.pts-Papple-iphone-xr-64gb-schwarz_h_6260 manual__2022-06-17T20:12:59.782916+00:00 [queued]>
[2022-06-17 20:13:03,716] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 20:13:03,716] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2022-06-17 20:13:03,716] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 20:13:03,736] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): pts-Papple-iphone-xr-64gb-schwarz_h_6260> on 2022-06-17 20:12:59.782916+00:00
[2022-06-17 20:13:03,742] {standard_task_runner.py:52} INFO - Started process 4748 to run task
[2022-06-17 20:13:03,887] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Job-pts', 'pts-Papple-iphone-xr-64gb-schwarz_h_6260', 'manual__2022-06-17T20:12:59.782916+00:00', '--job-id', '302', '--raw', '--subdir', 'DAGS_FOLDER/docker_job/price_scale.py', '--cfg-path', '/tmp/tmpc421owkt', '--error-file', '/tmp/tmpmr36x5vw']
[2022-06-17 20:13:03,916] {standard_task_runner.py:80} INFO - Job 302: Subtask pts-Papple-iphone-xr-64gb-schwarz_h_6260
[2022-06-17 20:13:04,984] {task_command.py:370} INFO - Running <TaskInstance: Job-pts.pts-Papple-iphone-xr-64gb-schwarz_h_6260 manual__2022-06-17T20:12:59.782916+00:00 [running]> on host 31bbb70af43b
[2022-06-17 20:13:08,436] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=samuel.momoh-olle@asgoodasnew.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Job-pts
AIRFLOW_CTX_TASK_ID=pts-Papple-iphone-xr-64gb-schwarz_h_6260
AIRFLOW_CTX_EXECUTION_DATE=2022-06-17T20:12:59.782916+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-17T20:12:59.782916+00:00
[2022-06-17 20:15:32,116] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/docker_job/price_scale.py", line 115, in test
    ppd = ProductPriceData(driver=webdriver.Chrome(executable_path="dags/docker_job/chromedriver", options=options))
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    service_log_path, service, keep_alive)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 98, in __init__
    options=options)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
Stacktrace:
#0 0x55fc8a3e3f33 <unknown>
#1 0x55fc8a12dfaf <unknown>
#2 0x55fc8a11c209 <unknown>
#3 0x55fc8a154a79 <unknown>
#4 0x55fc8a1509d0 <unknown>
#5 0x55fc8a14cd5a <unknown>
#6 0x55fc8a187d3a <unknown>
#7 0x55fc8a181e63 <unknown>
#8 0x55fc8a15782a <unknown>
#9 0x55fc8a158985 <unknown>
#10 0x55fc8a4284cd <unknown>
#11 0x55fc8a42c5ec <unknown>
#12 0x55fc8a41271e <unknown>
#13 0x55fc8a42d238 <unknown>
#14 0x55fc8a407870 <unknown>
#15 0x55fc8a449608 <unknown>
#16 0x55fc8a449788 <unknown>
#17 0x55fc8a463f1d <unknown>
#18 0x7efca5a80ea7 <unknown>

[2022-06-17 20:15:32,617] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Job-pts, task_id=pts-Papple-iphone-xr-64gb-schwarz_h_6260, execution_date=20220617T201259, start_date=20220617T201303, end_date=20220617T201532
[2022-06-17 20:15:32,671] {standard_task_runner.py:97} ERROR - Failed to execute job 302 for task pts-Papple-iphone-xr-64gb-schwarz_h_6260 (Message: chrome not reachable
Stacktrace:
#0 0x55fc8a3e3f33 <unknown>
#1 0x55fc8a12dfaf <unknown>
#2 0x55fc8a11c209 <unknown>
#3 0x55fc8a154a79 <unknown>
#4 0x55fc8a1509d0 <unknown>
#5 0x55fc8a14cd5a <unknown>
#6 0x55fc8a187d3a <unknown>
#7 0x55fc8a181e63 <unknown>
#8 0x55fc8a15782a <unknown>
#9 0x55fc8a158985 <unknown>
#10 0x55fc8a4284cd <unknown>
#11 0x55fc8a42c5ec <unknown>
#12 0x55fc8a41271e <unknown>
#13 0x55fc8a42d238 <unknown>
#14 0x55fc8a407870 <unknown>
#15 0x55fc8a449608 <unknown>
#16 0x55fc8a449788 <unknown>
#17 0x55fc8a463f1d <unknown>
#18 0x7efca5a80ea7 <unknown>
; 4748)
[2022-06-17 20:15:32,696] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-17 20:15:32,932] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
