[2022-06-18 13:09:00,616] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Job-pts.pts-Papple-iphone-xs-max-256gb-space-grau_h_6254 scheduled__2022-06-18T10:22:20.706366+00:00 [None]>
[2022-06-18 13:09:00,986] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Job-pts.pts-Papple-iphone-xs-max-256gb-space-grau_h_6254 scheduled__2022-06-18T10:22:20.706366+00:00 [None]>
[2022-06-18 13:09:00,986] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-18 13:09:00,986] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2022-06-18 13:09:00,986] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-18 13:09:01,405] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): pts-Papple-iphone-xs-max-256gb-space-grau_h_6254> on 2022-06-18 10:22:20.706366+00:00
[2022-06-18 13:09:01,583] {standard_task_runner.py:52} INFO - Started process 6182 to run task
[2022-06-18 13:09:01,906] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Job-pts', 'pts-Papple-iphone-xs-max-256gb-space-grau_h_6254', 'scheduled__2022-06-18T10:22:20.706366+00:00', '--job-id', '449', '--raw', '--subdir', 'DAGS_FOLDER/docker_job/price_scale.py', '--cfg-path', '/tmp/tmpxjjbv10w', '--error-file', '/tmp/tmpcj_f_l0g']
[2022-06-18 13:09:01,907] {standard_task_runner.py:80} INFO - Job 449: Subtask pts-Papple-iphone-xs-max-256gb-space-grau_h_6254
[2022-06-18 13:09:02,483] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/configuration.py:525: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-06-18 13:09:03,966] {task_command.py:370} INFO - Running <TaskInstance: Job-pts.pts-Papple-iphone-xs-max-256gb-space-grau_h_6254 scheduled__2022-06-18T10:22:20.706366+00:00 [running]> on host 2d9e52ec85d2
[2022-06-18 13:09:13,503] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=samuel.momoh-olle@asgoodasnew.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Job-pts
AIRFLOW_CTX_TASK_ID=pts-Papple-iphone-xs-max-256gb-space-grau_h_6254
AIRFLOW_CTX_EXECUTION_DATE=2022-06-18T10:22:20.706366+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-18T10:22:20.706366+00:00
[2022-06-18 13:13:32,585] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/docker_job/price_scale.py", line 115, in test
    ppd = ProductPriceData(driver=webdriver.Chrome(executable_path="dags/docker_job/chromedriver", options=options))
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    service_log_path, service, keep_alive)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 98, in __init__
    options=options)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
Stacktrace:
#0 0x560e34cb0f33 <unknown>
#1 0x560e349fb118 <unknown>
#2 0x560e34a21282 <unknown>
#3 0x560e34a1d7c6 <unknown>
#4 0x560e34a19d5a <unknown>
#5 0x560e34a54d3a <unknown>
#6 0x560e34a4ee63 <unknown>
#7 0x560e34a2482a <unknown>
#8 0x560e34a25985 <unknown>
#9 0x560e34cf54cd <unknown>
#10 0x560e34cf95ec <unknown>
#11 0x560e34cdf71e <unknown>
#12 0x560e34cfa238 <unknown>
#13 0x560e34cd4870 <unknown>
#14 0x560e34d16608 <unknown>
#15 0x560e34d16788 <unknown>
#16 0x560e34d30f1d <unknown>
#17 0x7f9a6b786ea7 <unknown>

[2022-06-18 13:13:53,739] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Job-pts, task_id=pts-Papple-iphone-xs-max-256gb-space-grau_h_6254, execution_date=20220618T102220, start_date=20220618T130900, end_date=20220618T131353
[2022-06-18 13:13:53,862] {standard_task_runner.py:97} ERROR - Failed to execute job 449 for task pts-Papple-iphone-xs-max-256gb-space-grau_h_6254 (Message: unknown error: DevToolsActivePort file doesn't exist
Stacktrace:
#0 0x560e34cb0f33 <unknown>
#1 0x560e349fb118 <unknown>
#2 0x560e34a21282 <unknown>
#3 0x560e34a1d7c6 <unknown>
#4 0x560e34a19d5a <unknown>
#5 0x560e34a54d3a <unknown>
#6 0x560e34a4ee63 <unknown>
#7 0x560e34a2482a <unknown>
#8 0x560e34a25985 <unknown>
#9 0x560e34cf54cd <unknown>
#10 0x560e34cf95ec <unknown>
#11 0x560e34cdf71e <unknown>
#12 0x560e34cfa238 <unknown>
#13 0x560e34cd4870 <unknown>
#14 0x560e34d16608 <unknown>
#15 0x560e34d16788 <unknown>
#16 0x560e34d30f1d <unknown>
#17 0x7f9a6b786ea7 <unknown>
; 6182)
[2022-06-18 13:13:53,945] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-18 13:13:54,869] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
