[2022-06-18 08:47:54,555] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Job-pts.pts-Papple-iphone-xs-256gb-space-grau_h_6245 scheduled__2022-06-17T22:40:58.837877+00:00 [queued]>
[2022-06-18 08:47:55,802] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Job-pts.pts-Papple-iphone-xs-256gb-space-grau_h_6245 scheduled__2022-06-17T22:40:58.837877+00:00 [queued]>
[2022-06-18 08:47:55,804] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-18 08:47:55,804] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2022-06-18 08:47:55,804] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-18 08:47:55,940] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): pts-Papple-iphone-xs-256gb-space-grau_h_6245> on 2022-06-17 22:40:58.837877+00:00
[2022-06-18 08:47:55,956] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Job-pts', 'pts-Papple-iphone-xs-256gb-space-grau_h_6245', 'scheduled__2022-06-17T22:40:58.837877+00:00', '--job-id', '357', '--raw', '--subdir', 'DAGS_FOLDER/docker_job/price_scale.py', '--cfg-path', '/tmp/tmptk916w34', '--error-file', '/tmp/tmpf19kdmfe']
[2022-06-18 08:47:55,957] {standard_task_runner.py:80} INFO - Job 357: Subtask pts-Papple-iphone-xs-256gb-space-grau_h_6245
[2022-06-18 08:47:55,948] {standard_task_runner.py:52} INFO - Started process 2184 to run task
[2022-06-18 08:47:56,078] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/configuration.py:525: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-06-18 08:47:56,618] {task_command.py:370} INFO - Running <TaskInstance: Job-pts.pts-Papple-iphone-xs-256gb-space-grau_h_6245 scheduled__2022-06-17T22:40:58.837877+00:00 [running]> on host 31bbb70af43b
[2022-06-18 08:47:57,958] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=samuel.momoh-olle@asgoodasnew.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Job-pts
AIRFLOW_CTX_TASK_ID=pts-Papple-iphone-xs-256gb-space-grau_h_6245
AIRFLOW_CTX_EXECUTION_DATE=2022-06-17T22:40:58.837877+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-17T22:40:58.837877+00:00
[2022-06-18 08:49:41,491] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/docker_job/price_scale.py", line 115, in test
    ppd = ProductPriceData(driver=webdriver.Chrome(executable_path="dags/docker_job/chromedriver", options=options))
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    service_log_path, service, keep_alive)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 98, in __init__
    options=options)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
Stacktrace:
#0 0x55b4e9304f33 <unknown>
#1 0x55b4e904f118 <unknown>
#2 0x55b4e9075282 <unknown>
#3 0x55b4e90717c6 <unknown>
#4 0x55b4e906dd5a <unknown>
#5 0x55b4e90a8d3a <unknown>
#6 0x55b4e90a2e63 <unknown>
#7 0x55b4e907882a <unknown>
#8 0x55b4e9079985 <unknown>
#9 0x55b4e93494cd <unknown>
#10 0x55b4e934d5ec <unknown>
#11 0x55b4e933371e <unknown>
#12 0x55b4e934e238 <unknown>
#13 0x55b4e9328870 <unknown>
#14 0x55b4e936a608 <unknown>
#15 0x55b4e936a788 <unknown>
#16 0x55b4e9384f1d <unknown>
#17 0x7f17565f2ea7 <unknown>

[2022-06-18 08:49:44,934] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Job-pts, task_id=pts-Papple-iphone-xs-256gb-space-grau_h_6245, execution_date=20220617T224058, start_date=20220618T084754, end_date=20220618T084944
[2022-06-18 08:49:46,447] {standard_task_runner.py:97} ERROR - Failed to execute job 357 for task pts-Papple-iphone-xs-256gb-space-grau_h_6245 (Message: unknown error: DevToolsActivePort file doesn't exist
Stacktrace:
#0 0x55b4e9304f33 <unknown>
#1 0x55b4e904f118 <unknown>
#2 0x55b4e9075282 <unknown>
#3 0x55b4e90717c6 <unknown>
#4 0x55b4e906dd5a <unknown>
#5 0x55b4e90a8d3a <unknown>
#6 0x55b4e90a2e63 <unknown>
#7 0x55b4e907882a <unknown>
#8 0x55b4e9079985 <unknown>
#9 0x55b4e93494cd <unknown>
#10 0x55b4e934d5ec <unknown>
#11 0x55b4e933371e <unknown>
#12 0x55b4e934e238 <unknown>
#13 0x55b4e9328870 <unknown>
#14 0x55b4e936a608 <unknown>
#15 0x55b4e936a788 <unknown>
#16 0x55b4e9384f1d <unknown>
#17 0x7f17565f2ea7 <unknown>
; 2184)
[2022-06-18 08:49:46,520] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-18 08:49:47,355] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
