[2022-06-15 20:46:35,542] {processor.py:153} INFO - Started process (PID=72) to work on /opt/airflow/dags/docker_job/pricing/vars.py
[2022-06-15 20:46:35,543] {processor.py:641} INFO - Processing file /opt/airflow/dags/docker_job/pricing/vars.py for tasks to queue
[2022-06-15 20:46:35,543] {logging_mixin.py:115} INFO - [2022-06-15 20:46:35,543] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/docker_job/pricing/vars.py
[2022-06-15 20:46:35,694] {logging_mixin.py:115} INFO - [2022-06-15 20:46:35,693] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/docker_job/pricing/vars.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    creationflags=self.creationflags)
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'opt/airflow/dags/docker_job/chromedriver': 'opt/airflow/dags/docker_job/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/docker_job/pricing/vars.py", line 24, in <module>
    driver = webdriver.Chrome(executable_path="opt/airflow/dags/docker_job/chromedriver", options=options)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    service_log_path, service, keep_alive)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home
[2022-06-15 20:46:35,695] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/docker_job/pricing/vars.py
[2022-06-15 20:46:35,707] {processor.py:161} INFO - Processing /opt/airflow/dags/docker_job/pricing/vars.py took 0.168 seconds
[2022-06-15 20:47:05,855] {processor.py:153} INFO - Started process (PID=78) to work on /opt/airflow/dags/docker_job/pricing/vars.py
[2022-06-15 20:47:05,856] {processor.py:641} INFO - Processing file /opt/airflow/dags/docker_job/pricing/vars.py for tasks to queue
[2022-06-15 20:47:05,857] {logging_mixin.py:115} INFO - [2022-06-15 20:47:05,856] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/docker_job/pricing/vars.py
[2022-06-15 20:47:05,984] {logging_mixin.py:115} INFO - [2022-06-15 20:47:05,983] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/docker_job/pricing/vars.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    creationflags=self.creationflags)
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'opt/airflow/dags/docker_job/chromedriver': 'opt/airflow/dags/docker_job/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/docker_job/pricing/vars.py", line 24, in <module>
    driver = webdriver.Chrome(executable_path="opt/airflow/dags/docker_job/chromedriver", options=options)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    service_log_path, service, keep_alive)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home
[2022-06-15 20:47:05,984] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/docker_job/pricing/vars.py
[2022-06-15 20:47:05,998] {processor.py:161} INFO - Processing /opt/airflow/dags/docker_job/pricing/vars.py took 0.145 seconds
[2022-06-15 20:47:36,157] {processor.py:153} INFO - Started process (PID=84) to work on /opt/airflow/dags/docker_job/pricing/vars.py
[2022-06-15 20:47:36,158] {processor.py:641} INFO - Processing file /opt/airflow/dags/docker_job/pricing/vars.py for tasks to queue
[2022-06-15 20:47:36,159] {logging_mixin.py:115} INFO - [2022-06-15 20:47:36,158] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/docker_job/pricing/vars.py
[2022-06-15 20:47:36,201] {logging_mixin.py:115} INFO - [2022-06-15 20:47:36,200] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/docker_job/pricing/vars.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    creationflags=self.creationflags)
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'opt/airflow/dags/docker_job/chromedriver': 'opt/airflow/dags/docker_job/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/docker_job/pricing/vars.py", line 24, in <module>
    driver = webdriver.Chrome(executable_path="opt/airflow/dags/docker_job/chromedriver", options=options)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    service_log_path, service, keep_alive)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home
[2022-06-15 20:47:36,202] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/docker_job/pricing/vars.py
[2022-06-15 20:47:36,219] {processor.py:161} INFO - Processing /opt/airflow/dags/docker_job/pricing/vars.py took 0.064 seconds
[2022-06-15 20:48:06,416] {processor.py:153} INFO - Started process (PID=90) to work on /opt/airflow/dags/docker_job/pricing/vars.py
[2022-06-15 20:48:06,417] {processor.py:641} INFO - Processing file /opt/airflow/dags/docker_job/pricing/vars.py for tasks to queue
[2022-06-15 20:48:06,417] {logging_mixin.py:115} INFO - [2022-06-15 20:48:06,417] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/docker_job/pricing/vars.py
[2022-06-15 20:48:06,456] {logging_mixin.py:115} INFO - [2022-06-15 20:48:06,455] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/docker_job/pricing/vars.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    creationflags=self.creationflags)
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'opt/airflow/dags/docker_job/chromedriver': 'opt/airflow/dags/docker_job/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/docker_job/pricing/vars.py", line 24, in <module>
    driver = webdriver.Chrome(executable_path="opt/airflow/dags/docker_job/chromedriver", options=options)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    service_log_path, service, keep_alive)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home
[2022-06-15 20:48:06,457] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/docker_job/pricing/vars.py
[2022-06-15 20:48:06,473] {processor.py:161} INFO - Processing /opt/airflow/dags/docker_job/pricing/vars.py took 0.060 seconds
[2022-06-15 20:48:36,640] {processor.py:153} INFO - Started process (PID=96) to work on /opt/airflow/dags/docker_job/pricing/vars.py
[2022-06-15 20:48:36,641] {processor.py:641} INFO - Processing file /opt/airflow/dags/docker_job/pricing/vars.py for tasks to queue
[2022-06-15 20:48:36,642] {logging_mixin.py:115} INFO - [2022-06-15 20:48:36,642] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/docker_job/pricing/vars.py
[2022-06-15 20:48:36,681] {logging_mixin.py:115} INFO - [2022-06-15 20:48:36,680] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/docker_job/pricing/vars.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    creationflags=self.creationflags)
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'opt/airflow/dags/docker_job/chromedriver': 'opt/airflow/dags/docker_job/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/docker_job/pricing/vars.py", line 24, in <module>
    driver = webdriver.Chrome(executable_path="opt/airflow/dags/docker_job/chromedriver", options=options)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    service_log_path, service, keep_alive)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home
[2022-06-15 20:48:36,681] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/docker_job/pricing/vars.py
[2022-06-15 20:48:36,696] {processor.py:161} INFO - Processing /opt/airflow/dags/docker_job/pricing/vars.py took 0.060 seconds
[2022-06-15 20:49:06,912] {processor.py:153} INFO - Started process (PID=102) to work on /opt/airflow/dags/docker_job/pricing/vars.py
[2022-06-15 20:49:06,913] {processor.py:641} INFO - Processing file /opt/airflow/dags/docker_job/pricing/vars.py for tasks to queue
[2022-06-15 20:49:06,913] {logging_mixin.py:115} INFO - [2022-06-15 20:49:06,913] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/docker_job/pricing/vars.py
[2022-06-15 20:49:06,952] {logging_mixin.py:115} INFO - [2022-06-15 20:49:06,951] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/docker_job/pricing/vars.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    creationflags=self.creationflags)
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'opt/airflow/dags/docker_job/chromedriver': 'opt/airflow/dags/docker_job/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/docker_job/pricing/vars.py", line 24, in <module>
    driver = webdriver.Chrome(executable_path="opt/airflow/dags/docker_job/chromedriver", options=options)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    service_log_path, service, keep_alive)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home
[2022-06-15 20:49:06,952] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/docker_job/pricing/vars.py
[2022-06-15 20:49:06,968] {processor.py:161} INFO - Processing /opt/airflow/dags/docker_job/pricing/vars.py took 0.058 seconds
[2022-06-15 20:49:17,951] {processor.py:153} INFO - Started process (PID=104) to work on /opt/airflow/dags/docker_job/pricing/vars.py
[2022-06-15 20:49:17,952] {processor.py:641} INFO - Processing file /opt/airflow/dags/docker_job/pricing/vars.py for tasks to queue
[2022-06-15 20:49:17,952] {logging_mixin.py:115} INFO - [2022-06-15 20:49:17,952] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/docker_job/pricing/vars.py
[2022-06-15 20:49:17,952] {logging_mixin.py:115} INFO - [2022-06-15 20:49:17,952] {dagbag.py:300} INFO - File /opt/airflow/dags/docker_job/pricing/vars.py assumed to contain no DAGs. Skipping.
[2022-06-15 20:49:17,953] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/docker_job/pricing/vars.py
[2022-06-15 20:49:17,966] {processor.py:161} INFO - Processing /opt/airflow/dags/docker_job/pricing/vars.py took 0.018 seconds
