[2022-06-11 19:31:04,093] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: T-dbt-job-cdc_load.create_source_tables scheduled__2022-06-11T17:30:39.272850+00:00 [queued]>
[2022-06-11 19:31:04,110] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: T-dbt-job-cdc_load.create_source_tables scheduled__2022-06-11T17:30:39.272850+00:00 [queued]>
[2022-06-11 19:31:04,110] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-11 19:31:04,110] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-11 19:31:04,110] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-11 19:31:04,124] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_source_tables> on 2022-06-11 17:30:39.272850+00:00
[2022-06-11 19:31:04,133] {standard_task_runner.py:52} INFO - Started process 59 to run task
[2022-06-11 19:31:04,139] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'T-dbt-job-cdc_load', 'create_***_tables', 'scheduled__2022-06-11T17:30:39.272850+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/docker_job/dbt_test.py', '--cfg-path', '/tmp/tmp0lyhu_ng', '--error-file', '/tmp/tmps5i4hc_8']
[2022-06-11 19:31:04,140] {standard_task_runner.py:80} INFO - Job 2: Subtask create_***_tables
[2022-06-11 19:31:04,154] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/configuration.py:525: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-06-11 19:31:04,195] {task_command.py:370} INFO - Running <TaskInstance: T-dbt-job-cdc_load.create_source_tables scheduled__2022-06-11T17:30:39.272850+00:00 [running]> on host e926c0944008
[2022-06-11 19:31:04,260] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=samuelolle@yahoo.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=T-dbt-job-cdc_load
AIRFLOW_CTX_TASK_ID=create_***_tables
AIRFLOW_CTX_EXECUTION_DATE=2022-06-11T17:30:39.272850+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-11T17:30:39.272850+00:00
[2022-06-11 19:31:04,282] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 186, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 86, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `***` isn't defined
[2022-06-11 19:31:04,285] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=T-dbt-job-cdc_load, task_id=create_***_tables, execution_date=20220611T173039, start_date=20220611T193104, end_date=20220611T193104
[2022-06-11 19:31:04,296] {standard_task_runner.py:97} ERROR - Failed to execute job 2 for task create_***_tables (The conn_id `***` isn't defined; 59)
[2022-06-11 19:31:04,311] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-11 19:31:04,347] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
