[2022-06-16 11:41:50,894] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Job-pts.pts scheduled__2022-06-16T09:11:47.345967+00:00 [queued]>
[2022-06-16 11:41:50,902] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Job-pts.pts scheduled__2022-06-16T09:11:47.345967+00:00 [queued]>
[2022-06-16 11:41:50,902] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-16 11:41:50,902] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2022-06-16 11:41:50,902] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-16 11:41:50,913] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): pts> on 2022-06-16 09:11:47.345967+00:00
[2022-06-16 11:41:50,916] {standard_task_runner.py:52} INFO - Started process 9744 to run task
[2022-06-16 11:41:50,919] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Job-pts', 'pts', 'scheduled__2022-06-16T09:11:47.345967+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/docker_job/price_scale.py', '--cfg-path', '/tmp/tmpcpw8_qvf', '--error-file', '/tmp/tmpmwlk2xf3']
[2022-06-16 11:41:50,919] {standard_task_runner.py:80} INFO - Job 172: Subtask pts
[2022-06-16 11:41:50,933] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/configuration.py:525: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-06-16 11:41:50,967] {task_command.py:370} INFO - Running <TaskInstance: Job-pts.pts scheduled__2022-06-16T09:11:47.345967+00:00 [running]> on host 3c1ac2e19971
[2022-06-16 11:41:51,030] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=samuel.momoh-olle@asgoodasnew.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Job-pts
AIRFLOW_CTX_TASK_ID=pts
AIRFLOW_CTX_EXECUTION_DATE=2022-06-16T09:11:47.345967+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-16T09:11:47.345967+00:00
[2022-06-16 11:41:51,032] {logging_mixin.py:115} INFO - /opt/airflow
[2022-06-16 11:41:51,658] {logging_mixin.py:115} INFO - https://www.handyverkauf.net/apple-iphone-x-64gb-space-grau_h_5143
[2022-06-16 11:42:24,057] {logging_mixin.py:115} INFO - []
[2022-06-16 11:42:24,058] {python.py:173} INFO - Done. Returned value was: None
[2022-06-16 11:42:24,684] {logging_mixin.py:115} INFO - https://www.handyverkauf.net/apple-iphone-x-256gb-space-grau_h_5145
[2022-06-16 11:42:56,716] {logging_mixin.py:115} INFO - []
[2022-06-16 11:42:56,716] {python.py:173} INFO - Done. Returned value was: None
[2022-06-16 11:42:57,348] {logging_mixin.py:115} INFO - https://www.handyverkauf.net/apple-iphone-xs-64gb-space-grau_h_6242
[2022-06-16 11:43:27,929] {logging_mixin.py:115} INFO - []
[2022-06-16 11:43:27,929] {python.py:173} INFO - Done. Returned value was: None
[2022-06-16 11:43:28,557] {logging_mixin.py:115} INFO - https://www.handyverkauf.net/apple-iphone-xs-256gb-space-grau_h_6245
[2022-06-16 11:43:59,368] {logging_mixin.py:115} INFO - []
[2022-06-16 11:43:59,369] {python.py:173} INFO - Done. Returned value was: None
[2022-06-16 11:43:59,994] {logging_mixin.py:115} INFO - https://www.handyverkauf.net/apple-iphone-xs-512gb-space-grau_h_6248
[2022-06-16 11:44:31,087] {logging_mixin.py:115} INFO - []
[2022-06-16 11:44:31,088] {python.py:173} INFO - Done. Returned value was: None
[2022-06-16 11:44:31,740] {logging_mixin.py:115} INFO - https://www.handyverkauf.net/apple-iphone-xs-max-64gb-space-grau_h_6251
[2022-06-16 11:45:48,998] {logging_mixin.py:115} INFO - []
[2022-06-16 11:45:48,999] {python.py:173} INFO - Done. Returned value was: None
[2022-06-16 11:46:53,726] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/docker_job/price_scale.py", line 175, in run_from_class
    python_task.execute(dict())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/docker_job/price_scale.py", line 115, in test
    ppd = ProductPriceData(driver=webdriver.Chrome(executable_path="dags/docker_job/chromedriver", options=options))
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    service_log_path, service, keep_alive)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 98, in __init__
    options=options)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
Stacktrace:
#0 0x55b33cc59f33 <unknown>
#1 0x55b33c9a4118 <unknown>
#2 0x55b33c9ca282 <unknown>
#3 0x55b33c9c67c6 <unknown>
#4 0x55b33c9c2d5a <unknown>
#5 0x55b33c9fdd3a <unknown>
#6 0x55b33c9f7e63 <unknown>
#7 0x55b33c9cd82a <unknown>
#8 0x55b33c9ce985 <unknown>
#9 0x55b33cc9e4cd <unknown>
#10 0x55b33cca25ec <unknown>
#11 0x55b33cc8871e <unknown>
#12 0x55b33cca3238 <unknown>
#13 0x55b33cc7d870 <unknown>
#14 0x55b33ccbf608 <unknown>
#15 0x55b33ccbf788 <unknown>
#16 0x55b33ccd9f1d <unknown>
#17 0x7f165f403ea7 <unknown>

[2022-06-16 11:46:54,678] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Job-pts, task_id=pts, execution_date=20220616T091147, start_date=20220616T114150, end_date=20220616T114654
[2022-06-16 11:46:54,879] {standard_task_runner.py:97} ERROR - Failed to execute job 172 for task pts (Message: unknown error: DevToolsActivePort file doesn't exist
Stacktrace:
#0 0x55b33cc59f33 <unknown>
#1 0x55b33c9a4118 <unknown>
#2 0x55b33c9ca282 <unknown>
#3 0x55b33c9c67c6 <unknown>
#4 0x55b33c9c2d5a <unknown>
#5 0x55b33c9fdd3a <unknown>
#6 0x55b33c9f7e63 <unknown>
#7 0x55b33c9cd82a <unknown>
#8 0x55b33c9ce985 <unknown>
#9 0x55b33cc9e4cd <unknown>
#10 0x55b33cca25ec <unknown>
#11 0x55b33cc8871e <unknown>
#12 0x55b33cca3238 <unknown>
#13 0x55b33cc7d870 <unknown>
#14 0x55b33ccbf608 <unknown>
#15 0x55b33ccbf788 <unknown>
#16 0x55b33ccd9f1d <unknown>
#17 0x7f165f403ea7 <unknown>
; 9744)
[2022-06-16 11:46:55,122] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-16 11:46:55,233] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
